baseURL = ""
languageCode = "en"
defaultContentLanguage = "en"
title = "Hallo"
theme = "hallo"
disableKinds = [ "page", "section", "taxonomy", "taxonomyTerm" ]
themesDir = "themes"
publishDir = "public"

[Author]
name = "Andrew Bunker"

[[params.links]]
iconset = "fas"
icon = "envelope"
title = "E-mail"
url = "mailto:andrew.thomas.bunker@gmail.com"

[[params.links]]
icon = "github"
title = "Github"
url = "https://github.com/"

[[params.links]]
icon = "twitter"
title = "Twitter"
url = "https://twitter.com/"
